import { colorSettings } from './Colors.styles';

const {
  darkText,
  buttonText,
  buttonBackground,
  textInputBackground,
  textInputText,
  textInputBorder,
} = colorSettings;
const generalFont = 'Thasadith-Regular';
const generalFontBold = 'Thasadith-Bold';

const generalStyling = {
  h1: {
    fontFamily: generalFontBold,
    fontSize: 20,
    color: darkText,
  },
  h2: {
    fontFamily: generalFontBold,
    fontSize: 16,
    color: darkText,
  },
  h3: {
    fontFamily: generalFontBold,
    fontSize: 14,
    color: darkText,
  },
  normal: {
    fontFamily: generalFont,
    fontSize: 12,
    color: darkText,
  },
  checkbox: {
    title: { fontFamily: generalFont, fontSize: 12 },
  },
  textInput: {
    height: 40,
    width: '90%',
    borderColor: textInputBorder,
    borderWidth: 1,
    marginTop: 8,
    backgroundColor: textInputBackground,
    color: textInputText,
    paddingLeft: 5,
  },
  button: {
    marginTop: 5,
    backgroundColor: buttonBackground,
    fontFamily: generalFontBold,
    padding: 10,
    width: 70,
    justifyContent: 'center',
  },
  buttonText: {
    fontFamily: generalFontBold,
    fontSize: 14,
    color: buttonText,
  },
};

export { generalFont, generalStyling };

// Valid keys: [
//   "display",
//   "width",
//   "height",
//   "start",
//   "end",
//   "top",
//   "left",
//   "right",
//   "bottom",
//   "minWidth",
//   "maxWidth",
//   "minHeight",
//   "maxHeight",
//   "margin",
//   "marginVertical",
//   "marginHorizontal",
//   "marginTop",
//   "marginBottom",
//   "marginLeft",
//   "marginRight",
//   "marginStart",
//   "marginEnd",
//   "padding",
//   "paddingVertical",
//   "paddingHorizontal",
//   "paddingTop",
//   "paddingBottom",
//   "paddingLeft",
//   "paddingRight",
//   "paddingStart",
//   "paddingEnd",
//   "borderWidth",
//   "borderTopWidth",
//   "borderStartWidth",
//   "borderEndWidth",
//   "borderRightWidth",
//   "borderBottomWidth",
//   "borderLeftWidth",
//   "position",
//   "flexDirection",
//   "flexWrap",
//   "justifyContent",
//   "alignItems",
//   "alignSelf",
//   "alignContent",
//   "overflow",
//   "flex",
//   "flexGrow",
//   "flexShrink",
//   "flexBasis",
//   "aspectRatio",
//   "zIndex",
//   "direction",
//   "shadowColor",
//   "shadowOffset",
//   "shadowOpacity",
//   "shadowRadius",
//   "transform",
//   "transformMatrix",
//   "decomposedMatrix",
//   "scaleX",
//   "scaleY",
//   "rotation",
//   "translateX",
//   "translateY",
//   "backfaceVisibility",
//   "backgroundColor",
//   "borderColor",
//   "borderTopColor",
//   "borderRightColor",
//   "borderBottomColor",
//   "borderLeftColor",
//   "borderStartColor",
//   "borderEndColor",
//   "borderRadius",
//   "borderTopLeftRadius",
//   "borderTopRightRadius",
//   "borderTopStartRadius",
//   "borderTopEndRadius",
//   "borderBottomLeftRadius",
//   "borderBottomRightRadius",
//   "borderBottomStartRadius",
//   "borderBottomEndRadius",
//   "borderStyle",
//   "opacity",
//   "elevation",
//   "color",
//   "fontFamily",
//   "fontSize",
//   "fontStyle",
//   "fontWeight",
//   "fontVariant",
//   "textShadowOffset",
//   "textShadowRadius",
//   "textShadowColor",
//   "letterSpacing",
//   "lineHeight",
//   "textAlign",
//   "textAlignVertical",
//   "includeFontPadding",
//   "textDecorationLine",
//   "textDecorationStyle",
//   "textDecorationColor",
//   "textTransform",
//   "writingDirection"
// ]
